[project]
name = "kingaai-kweli"
version = "0.0.1"
license = {text = "Apache-2.0"}
requires-python = ">=3.9"
description = "kweli library"
[project.dependencies]\nkingaai-core = {url = "https://github.com/kinga-ai/kinga-core/archive/refs/tags/v0.1.0.tar.gz"}\n
